### ISSUE TITLE
Error api

### ISSUE THREAD

**Issue by MaceoBasse** [M47Hs/godsunchained#5]
Hello,

There is an error in the function getAllProtos.
I can't get an answer from the api  "https://gy2601wgv6.execute-api.us-east-1.amazonaws.com/dev/all-orders"
I think I'm not allowed to call the api.
Is there any api documentation ?
What do I have to do to get an api key?

Maceo

**Comment by enitrat** [comment]
Hi,
Unfortunately this used to be Tokentrove's public API that is now private. I don't have an API Key either, so the website is basically dead and I won't be maintaining it anymore

You can visit this version instead : https://www.gumarket.io/
